# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/forecastra',
                'doc_host': 'https://maansisinghal.github.io',
                'git_url': 'https://github.com/maansisinghal/forecastra',
                'lib_path': 'forecastra'},
  'syms': {'forecastra.core': {'forecastra.core.foo': ('core.html#foo', 'forecastra/core.py')}}}
